import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import axios from 'axios';
import { baseUrl } from './_app';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [categories, setCategories] = useState([]);

  function getCategories() {
    axios.get(`${baseUrl}/api/user`).then(result => setCategories(result.data)).catch(error => console.log(error));
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <h1>{JSON.stringify(categories)}</h1>
          <button onClick={() => getCategories()}>Get categories</button>
        </div>
      </main>
    </>
  )
}
